version: "0.2"
ignorePaths:
  - "**/build/**/*"
  - "**/dist/**/*"
  - packages/*/src/prebuilt/**/*
  - packages/asr/src/asr.js
  - packages/vad/src/vad.js
  - packages/vad-asr/src/asr.js
  - packages/vad-asr/src/vad.js
  - packages/speaker-diarization/src/sherpa-onnx-wasm-main-speaker-diarization.js
  - pnpm-lock.yaml
  - sherpa-onnx/upstream/**/*
  - upstream/**/*
dictionaryDefinitions: []
dictionaries: []
words:
  - Attributify
  - audioworklet
  - Ayaka
  - bumpp
  - ccall
  - cjkchar
  - cwrap
  - demi
  - downsample
  - emcc
  - emscripten
  - emsdk
  - endforeach
  - endfunction
  - eventa
  - Fars
  - Fsts
  - HEAPF
  - HEAPU
  - hotwords
  - iconify
  - LIBSTDCPP
  - Makito
  - malloc
  - moeru
  - Neko
  - Nemo
  - npmjs
  - onnx
  - onnxruntime
  - paraformer
  - PORTAUDIO
  - Pyannote
  - reka
  - sherpaw
  - silero
  - sumimakito
  - Tdnn
  - tele
  - tsdown
  - unocss
  - unplugin
  - VADASR
  - vueuse
  - webworkers
  - Wenet
  - worklet
  - xlink
  - xsai
  - zipformer
ignoreWords: []
import: []
