version: "0.2"
ignorePaths:
  - "**/build/**/*"
  - "**/dist/**/*"
  - "**/.wrangler/**/*"
  - "**/*.tsbuildinfo"
  - "**/*.onnx"
  - models/**/*
  - packages/*/tests/model*/**/*
  - packages/*/src/prebuilt/**/*
  - packages/asr/src/asr.js
  - packages/vad/src/vad.js
  - packages/vad-asr/src/asr.js
  - packages/vad-asr/src/vad.js
  - packages/speaker-diarization/src/sherpa-onnx-wasm-main-speaker-diarization.js
  - pnpm-lock.yaml
  - sherpa-onnx/upstream/**/*
  - upstream/**/*
dictionaryDefinitions: []
dictionaries: []
words:
  - asyncify
  - COPYONLY
  - csukuangfj
  - DBUILD
  - DCMAKE
  - DFETCHCONTENT
  - DSHERPAW
  - eigen
  - hclust
  - kaldi
  - kaldifst
  - kissfft
  - networkidle
  - openfst
  - protobufjs
  - quantizer
  - sentencepiece
  - sess
  - unstub
  - unpaced
  - webgpu
  - workgroups
  - worktree
  - basemove
  - dawidd
  - formants
  - rubberband
  - AIHUBMIX
  - campplus
  - dspeaker
  - ECAPA
  - eres
  - fangjun
  - fbank
  - GMACs
  - JSEP
  - leijun
  - liudehua
  - netv
  - nonfinite
  - recongition
  - SOTA
  - Voxceleb
  - wespeaker
  - accum
  - AIRI
  - Attributify
  - AXCL
  - Axera
  - audioworklet
  - Ayaka
  - bumpp
  - Branchformer
  - ccall
  - cjkchar
  - chromedriver
  - Chromedriver
  - conv
  - cwrap
  - CUDA
  - demi
  - downsample
  - denoiser
  - Diacritization
  - diacritization
  - DPDF
  - DSHERPA
  - Eeuo
  - emcc
  - emscripten
  - emsdk
  - endforeach
  - endfunction
  - eventa
  - Fakemic
  - Fars
  - Fsts
  - funasr
  - GTCRN
  - HEAPF
  - HEAPU
  - hfup
  - hotwords
  - huggingface
  - iconify
  - Kokoro
  - LIBSTDCPP
  - LSTM
  - Makito
  - malloc
  - medasr
  - moeru
  - Neko
  - Nemo
  - noloop
  - NNAPI
  - npmjs
  - omnilingual
  - Omnilingual
  - onnx
  - onnxruntime
  - paraformer
  - PORTAUDIO
  - Punct
  - Pyannote
  - Qwen
  - qwen
  - reka
  - riscv
  - RKNN
  - RNNT
  - sherpaw
  - silero
  - Spacemi
  - Spleeter
  - sumimakito
  - taze
  - Tauri
  - Tdnn
  - tele
  - tinyexec
  - tsdown
  - unocss
  - unplugin
  - VITS
  - VADASR
  - vitest
  - vueuse
  - wavs
  - webworkers
  - Wenet
  - worklet
  - XNNPACK
  - xlink
  - xsai
  - zipformer
ignoreWords: []
import: []
