version: '0.2'
ignorePaths:
  - packages/asr/src/sherpa-onnx-wasm-main-asr.js
  - packages/speaker-diarization/src/sherpa-onnx-wasm-main-speaker-diarization.js
dictionaryDefinitions: []
dictionaries: []
words:
  - audioworklet
  - bumpp
  - ccall
  - cjkchar
  - cwrap
  - downsample
  - emcc
  - emscripten
  - emsdk
  - endforeach
  - Fars
  - Fsts
  - HEAPF
  - HEAPU
  - hotwords
  - iconify
  - LIBSTDCPP
  - Makito
  - malloc
  - Nemo
  - onnx
  - paraformer
  - PORTAUDIO
  - reka
  - Tdnn
  - tele
  - tsdown
  - unplugin
  - vueuse
  - Wenet
  - worklet
  - zipformer
ignoreWords: []
import: []
