packages:
  - playgrounds/xsai
  - packages/asr
  - packages/preloader
  - packages/sandbox
  - packages/shared
  - packages/speaker-diarization
  - packages/vad
  - packages/vad-asr
  - packages/xsai-transcription
