packages:
  - playgrounds/xsai
  - packages/asr
  - packages/preloader
  - packages/sandbox
  - packages/shared
  - packages/speaker-diarization
  - packages/speaker-identification
  - packages/testing-audio
  - packages/vad
  - packages/vad-asr
  - packages/vitest-plugin-fakemic
  - packages/xsai-transcription
allowBuilds:
  vue-demi: true
